### ISSUE TITLE
BOLT-LMM: Run BOLT-LMM for UKB data and make sure all is well

### ISSUE THREAD

**Issue by jpbeauch** [sihrus/riskprefsgwas#11]
Run BOLT-LMM for UKB data and make sure all is well

**Comment by sihrus** [comment]
These should probably be two separate issues.

On Mon, Dec 14, 2015 at 9:00 PM, jpbeauch <notifications@github.com> wrote:

> Assigned #11 <https://github.com/sihrus/riskprefsgwas/issues/11> to
> @sihrus <https://github.com/sihrus>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sihrus/riskprefsgwas/issues/11#event-491725355>.
>



-- 
Mark

**Comment by jpbeauch** [comment]
OK I'll separate these two issues now

**Comment by jpbeauch** [comment]
Mark confirmed that this issue can be closed during the call today
