### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by sihrus** [sihrus/riskprefsgwas#2]
this is a test issue. go ahead and try commenting, and then maybe close out the issue showing it's been "completed". maybe also try creating an issue and assign it to me.

**Comment by jpbeauch** [comment]
OK I'm trying to comment now and then I'll close this issue and create a new one

**Comment by sihrus** [comment]
Seeing what happens if I comment on an open issue.

On Monday, November 30, 2015, jpbeauch <notifications@github.com> wrote:

> Closed #2 <https://github.com/sihrus/riskprefsgwas/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sihrus/riskprefsgwas/issues/2#event-477849762>.
>


-- 
Mark

**Comment by sihrus** [comment]
Closed, I meant.

On Monday, November 30, 2015, Mark Fontana <markfontana@gmail.com> wrote:

> Seeing what happens if I comment on an open issue.
>
> On Monday, November 30, 2015, jpbeauch <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Closed #2 <https://github.com/sihrus/riskprefsgwas/issues/2>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sihrus/riskprefsgwas/issues/2#event-477849762>.
>>
>
>
> --
> Mark
>


-- 
Mark

**Comment by jpbeauch** [comment]
And what if I reply from my gmail account?
Can you see this response both in your inbox and on Github?

**Comment by sihrus** [comment]
Yes!

On Monday, November 30, 2015, jpbeauch <notifications@github.com> wrote:

> And what if I reply from my gmail account?
> Can you see this response both in your inbox and on Github?
>
> On Mon, Nov 30, 2015 at 11:07 AM, sihrus <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Closed, I meant.
> >
> > On Monday, November 30, 2015, Mark Fontana <markfontana@gmail.com
> <javascript:_e(%7B%7D,'cvml','markfontana@gmail.com');>> wrote:
> >
> > > Seeing what happens if I comment on an open issue.
> > >
> > > On Monday, November 30, 2015, jpbeauch <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > >> Closed #2 <https://github.com/sihrus/riskprefsgwas/issues/2>.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/sihrus/riskprefsgwas/issues/2#event-477849762>.
> > >>
> > >
> > >
> > > --
> > > Mark
> > >
> >
> >
> > --
> > Mark
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sihrus/riskprefsgwas/issues/2#issuecomment-160672914
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sihrus/riskprefsgwas/issues/2#issuecomment-160673697>.
>


-- 
Mark

**Comment by jpbeauch** [comment]
Nice
