### ISSUE TITLE
New test issue

### ISSUE THREAD

**Issue by jpbeauch** [sihrus/riskprefsgwas#3]
Hi, this is a test issue.
I still have to figure out how the Desktop app works -- I can't see the riksprefsgwas directory on it.

**Comment by sihrus** [comment]
You have to clone the repository on your desktop. (Which you can open and
edit like any other directory on your local drive.) Everytime you start
working you "sync" the two and, after working, push any changes to the
master copy on github. It automatically detects the exact differences
between your local copy and the master (and keeps track of updates). We can
discuss more on Wednesday

On Monday, November 30, 2015, jpbeauch <notifications@github.com> wrote:

> Assigned #3 <https://github.com/sihrus/riskprefsgwas/issues/3> to @sihrus
> <https://github.com/sihrus>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sihrus/riskprefsgwas/issues/3#event-477855604>.
>


-- 
Mark

**Comment by jpbeauch** [comment]
OK I'll try that later and then close that issue when I get this to work

**Comment by sihrus** [comment]
this is over
